### ISSUE TITLE
a8n: Need command to either run automation ignoring the cache and/or deleting the cache

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#115]

**Comment by mrnugget** [comment]
`src actions exec` takes a `-cache` directory flag, which is where it will cache results etc. If you use an empty directory as `-cache` then, well, the cache is empty.

In order to delete the cache, either delete the directory you specified, or delete the default cache directory, which you can see if you run `src actions -help`:

```
$ src actions exec -help 2>&1 | head -n 3
Usage of 'src actions exec':
  -cache string
        Directory for caching results. (default "$HOME/Library/Caches/sourcegraph-src/action-exec")
```

That's what it prints on my machine (macOS)

**Comment by mrnugget** [comment]
@ryan-blunden Does the above comment address your concern?

**Comment by ryan-blunden** [comment]
Yeah, and I've [added your above notes to the automation docs](https://github.com/sourcegraph/sourcegraph/pull/8510).
