### ISSUE TITLE
Remove inline dockerfile option

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#151]
I like the intention behind making it super simple to run a container without creating a Dockerfile, but what's the likelihood of this being used in a content change scenario?

The [example used in the docs](https://sourcegraph.com/github.com/sourcegraph/sourcegraph@61c81dd96206b3ad59ff175cbbc054ff4e984631/-/blob/doc/user/campaigns.md#L89) is valid for sure, but couldn't this be achieved by specifying `alpine:3` as the image, then supplying the `CMD` in the example as `args` instead?

Removing the option to me would simplify things, and allow code to be removed, all without losing functionality (just needs to be done in a different way).

**Comment by eseliger** [comment]
You actually hit a point here with that. 
In the prototype for remote execution, we don't even support that flag currently, and since it's pretty complicated to do something like 
```Dockerfile
FROM nginx
COPY nginx.conf /etc/nginx
```
where nginx.conf is a local file but executed remotely.

So to keep things simple, I think this is a good and reasonable change.
