### ISSUE TITLE
Add `src actions create` command to create actions.json boilerplate

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/src-cli#153]
To help surface the actions schema and show different step examples, create a `create-schema` command which would create an `action.json` file in the current directory. I'd advise skipping the dumping it to stdout so the user can successfully do it the first time around without re-executing it with redirection to a file.

In the boilerplate file, a [`$schema`](https://github.com/sourcegraph/src-cli/pull/149#issuecomment-593668192) field would be added to surface the schema. 

This would make tutorial videos and instructions for creating an initial `action.json` file super easy and preconfiguring support for code completion and code doc hovers in VS Code would be really cool.

**Comment by mrnugget** [comment]
Nice idea. I think maybe we can make that more generic and instead of `src actions create-schema` (it doesn't create _the schema_, right? It creates a template that is based on the schema) we can have a `src actions create` command.

In a first version, `src actions create` would just create an `action.json` file with the `$schema` attribute.

The next version could include an `--interactive` flag where you get a prompt to interactively create a `scopeQuery`?

**Comment by ryan-blunden** [comment]
> In a first version, src actions create would just create an action.json file with the $schema attribute.

Perfect!

> The next version could include an --interactive flag where you get a prompt to interactively create a scopeQuery?

That would be amazing.
