### ISSUE TITLE
Deprecate config file

### ISSUE THREAD

**Issue by eseliger** [sourcegraph/src-cli#156]
~To be aligned with what other tools do, I want to propose that we rename the src-cli config file to a hidden file.~

See discussion below, we've decided to deprecate the config file.

**Comment by creachadair** [comment]
I like this idea in general, but rather than add yet-another hidden file to `$HOME` I suggest we use a more principled location, e.g. https://godoc.org/os#UserConfigDir.

**Comment by ryan-blunden** [comment]
As a macOS User, I always expect config files for CLI tools to be in the root as a hidden (dot) file. Configure for macOS apps on the other hand I do expect to be in the ‘Library/Application Support’ folder.

Regardless, does the src CLI default help output contain the path to the configuration file for the platform?

**Comment by slimsag** [comment]
In retrospect, I definitely regret placing the config file in `$HOME/src-config.json` -- that was silly of me. The `src` CLI was a quick 4hr hack project initially, I briefly considered a hidden file but thought that would make it harder to discover for some naive reason. 

Alternative proposal: Deprecate the config file entirely. I no longer believe it is the right method for configuring the `src` CLI because:

1. In scripting use cases, it is almost always the case that you will want to configure it with env variables. I have never once observed anyone prefer doing this via a config file.
2. In dev environment setups, configuring env variables is far easier and more familiar than writing config files in JSON.
3. The original motivation for using a config file was that "you might want to change the endpoint depending on the context you are working in (closed source vs. open source code)" but this is easier done with dotenv or similar.

This could be done by simply:

1. Undocumenting the `-config` flag
2. Ensuring the env variables work as expected and are documented in the README and anywhere else (check docs.sourcegraph.com).

@ryan-blunden Yes, `src -h` does report it:

```
[...]
The options are:
	-config=$HOME/src-config.json    specifies a file containing {"accessToken": "<secret>", "endpoint": "https://sourcegraph.com"}
[...]
```

**Comment by mrnugget** [comment]
> Alternative proposal: Deprecate the config file entirely. I no longer believe it is the right method for configuring the `src` CLI because:

I think this is the better approach. I configure the `src` CLI with `.env` files in different folders and it works really well, especially since all the other tokens/URLs for other tools/external-services are also configured right next to them.

**Comment by ryan-blunden** [comment]
Sounds good to me!

**Comment by ryanslade** [comment]
I'd like to take this for 3.17

**Comment by sqs** [comment]
How should we handle the case when the user has multiple Sourcegraph instances? Just expect them to set the env vars as needed?

(This is not trivially solved by config files either. We could have a config file that lets you define multiple endpoints, with a token for each, but then you'd need a way to tell `src` which endpoint you want to use, which starts to get kinda confusing.)

**Comment by ryanslade** [comment]
I think that expecting the user to set the correct env variable is fine. I would think that most of the time they'll only be using one instance and setting env vars to use additional instances seems fairly low effort for technical users.
