### ISSUE TITLE
Add more details on lsif upload failure

### ISSUE THREAD

**Issue by jjwon0** [sourcegraph/src-cli#330]
I'm guessing this could be an endpoint access error but I can't really dig too much into this since the error is fairly obtuse. A `-verbose` option could be helpful here!

```
jwon@jwon-dbx:~/src/server$ src lsif upload
Inferred arguments:
  -repo=<removed>
  -commit=<removed>
  -root=
  -file=./dump.lsif
  -indexer=lsif-go

invalid character '<' looking for beginning of value
```

**Comment by jjwon0** [comment]
As an addendum, I found the [auth proxy](https://github.com/sourcegraph/src-cli/blob/main/AUTH_PROXY.md) docs and was able to get it to work in some setups, but in other setups I'm still having trouble. Having any additional verbose logging would make this much less painful.

**Comment by efritz** [comment]
This should be a bit better in the 3.21.3 release found [here](https://github.com/sourcegraph/src-cli/releases/tag/3.21.3). I'll also look at making the upload output a bit more verbose (when enabled) so that if subsequent requests have issues they will also be user-visible.

Sorry for hiding all the dirty laundry here! :)
