### ISSUE TITLE
Invalid mount config for type "bind" when previewing campaign

### ISSUE THREAD

**Issue by evanweible-wf** [sourcegraph/src-cli#405]
I hit this error when trying to preview a campaign locally on my Mac. The campaign spec uses a docker container that I've built locally and is pretty simple. I tried `-clear-cache` with no effect. Then I tried `-cache /tmp/sg`, which got me to past this error.

CLI version:

```bash
$ src version
Current version: 3.22.4
Recommended Version: 3.22.4
```

Local dockerfile:

```Dockerfile
FROM google/dart:2.7
ADD pkg/ /pkg/
RUN pub global activate -spath /pkg/pubspec_codemod
```

Command output:

```bash
src campaigns preview -f campaigns/example/upgrade_package_test/campaign.yaml     [13:33:50]
✅ Parsing campaign spec
✅ Resolving namespace
✅ Preparing container images
✅ Resolved repositories
✅ Executing steps in 1 repositories
│                                                                                                                                     
└── github.com/Workiva/fluri  docker: Error response from daemon: invalid mount config for type "bind": bind source path does n...  1s

❌ Error:
   github.com/Workiva/fluri:
   run: pubspec_codemod override test 2.0.0 -f test
   container: pubspec_codemod:latest
   
   standard error:
        docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/evanweible/Library/Caches/sourcegraph/campaigns/workspace-github.com-Workiva-fluri832796938.
        See 'docker run --help'.
   
   Command failed with exit code 125.
   Log: /tmp/changeset-github.com-Workiva-fluri.102271127.log
```

Log file:

```txt
2020-12-11T13:33:57.0437-08:00 [Step 1] run: "pubspec_codemod override test 2.0.0 -f test", container: "pubspec_codemod:latest"
2020-12-11T13:33:57.043793-08:00 [Step 1] full command: "docker run --rm --init --cidfile /tmp/github.com-Workiva-fluri-container-id426444001 --workdir /work --mount type=bind,source=/Users/evanweible/Library/Caches/sourcegraph/campaigns/workspace-github.com-Workiva-fluri832796938,target=/work --mount type=bind,source=/tmp/138660044,target=/tmp/tmp.xRq7MDtHO7,ro --entrypoint /bin/bash -- sha256:1ce902ef018a934a0e8d97cdd01c55f41a6193438fca91576b88fb23d61002f6 /tmp/tmp.xRq7MDtHO7"
2020-12-11T13:33:57.319393-08:00 stderr | docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /host_mnt/Users/evanweible/Library/Caches/sourcegraph/campaigns/workspace-github.com-Workiva-fluri832796938.
2020-12-11T13:33:57.319442-08:00 stderr | See 'docker run --help'.
2020-12-11T13:33:57.31946-08:00 stderr | 
2020-12-11T13:33:57.32479-08:00 [Step 1] took 281ms; error running Docker container: exit status 125
```

**Comment by mrnugget** [comment]
Thanks for reporting! @evanweible-wf which version of Docker do you have?

**Comment by evanweible-wf** [comment]
Docker Desktop 3.0.0
Engine 20.10.0

I did just notice that there's a Docker update available, so I can try that.

**Comment by mrnugget** [comment]
I just upgraded from Docker 2.4 to 3.0.1, hoping that 3.0.1 would've fixed this issue, but it's still broken.

Seems like it's a known issue: https://docs.docker.com/docker-for-mac/release-notes/#docker-desktop-community-301

> It is currently not possible to bind mount files within ~/Libary into a container. See docker/for-mac#5115.

That breaks `src` since we use `~/Library/Caches` as the cache directory (which is the default returned by Go's [`os.UserCacheDir`](https://golang.org/pkg/os/#UserCacheDir)).

**Workaround until Docker releases a fix**: use another cache directory for `src` by using the `-cache` flag. Example:

```bash
$ export SRC_CACHE_DIR=$(mktemp -d)
$ src campaign preview -f hello-world.campaign.yaml -cache $SRC_CACHE_DIR
```

**Comment by mrnugget** [comment]
@LawnGnome Isn't this fixed with your new volume-mount mode?

**Comment by LawnGnome** [comment]
@mrnugget It is!

On Intel macOS, src-cli 3.23.2 or later will use a different mount mode by default, provided all the Docker images being used run as the same user. (The short version is that it will create a Docker volume and use that for the workspace, instead of bind mounting from the host filesystem.)

This also works on Windows, and _probably_ works on M1 Macs (alas, I don't have one to test with at present), but we're slow rolling changing the default to be on the safe side. That said, it's possible to force this anywhere by adding `-workspace volume` to the `src campaign preview` or `src campaign apply` command. Also adding `-v` will display which workspace mode is in use.

**Comment by evanweible-wf** [comment]
Awesome, thanks for the update!
