### ISSUE TITLE
pq: duplicate key value violates unique constraint error when trying to use src campaigns add-changeset

### ISSUE THREAD

**Issue by felixfbecker** [sourcegraph/src-cli#52]
I am trying to add a bunch of changesets to a campaign that has no changesets (according to the UI and GraphQL API).

I am running this command:
```powershell
 Get-GitHubPullRequest -Repository sourcegraph -Owner sourcegraph -State all | select-object -first 50 | % Number | % { src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' $_ }
```

Which runs these commands:
```powershell
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 6007
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 6006
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 6005
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 6003
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 5993
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 5991
src '-endpoint=http://localhost:3080' campaigns add-changesets '-campaign=Q2FtcGFpZ246MQ==' '-repo-name=github.com/sourcegraph/sourcegraph' 5990
...
```

But I am just getting this error printed every time:

```js
GraphQL errors:
[
  {
    "message": "pq: duplicate key value violates unique constraint \"changesets_repo_external_id_unique\"",
    "path": [
      "createChangesets"
    ]
  }
]
GraphQL errors:
[
  {
    "message": "pq: duplicate key value violates unique constraint \"changesets_repo_external_id_unique\"",
    "path": [
      "createChangesets"
    ]
  }
]
...
```

It works after dropping my entire database.

Maybe changesets are soft deleted, but there is a unique constraint on it that would block re-adding after being soft-deleted?

**Comment by mrnugget** [comment]
Is it possible that these changesets were already created for _another_ campaign?

What `src-cli` does is to `createChangesets` and then `addChangesetsToCampaign`. If the changeset already exists this will fail. 

In order to fix that, we'd have to make `createChangesets` idempotent so that you can call it multiple times and it doesn't error if a changeset has been created before. Quite easy to do if you have only one changeset, but since it's a batch operation, we'd have to take care of only creating the changesets that haven't been created before etc.

We choose not to do that the last time around and invest time in other issues, since this API won't likely be the most-used entry path to automation in the future.

**Comment by felixfbecker** [comment]
Is this something that will only affect the CLI though? It seems to me that the UI would have this same problem, and there is currently no way to work around it (there is no error code on the error, and there is no way to check which changesets exist).

Is there any benefit to have the separation between `createChangeset` and `addChangesetToCampaign` at all? I.e. is there any use case for creating  changesets in the DB without adding them to a campaign?

**Comment by mrnugget** [comment]
> Is this something that will only affect the CLI though? It seems to me that the UI would have this same problem, and there is currently no way to work around it (there is no error code on the error, and there is no way to check which changesets exist and get the ID of the existing changeset).

If we had an UI for this that would mimic this interface, it would have the same problem, yes.

But there are multiple ways to solve it. Once we do add an UI, we could add a GraphQL query that allows finding changesets by their external ID/repo. Or make the create operation idempotent. Or offer filtering by name and offer autocompletion. Or something else entirely.

(Since we chose not to add a UI for this yet, we decided not to add the necessary queries/mutations and only add those that make the simplest case for a script/`src-cli` work)

> Is there any benefit to have the separation between `createChangeset` and `addChangesetToCampaign` at all? I.e. is there any use case for creating changesets in the DB without adding them to a campaign?

The use case was/is: create a changeset and then add it to multiple campaigns. You want to add them to multiple campaigns.
