### ISSUE TITLE
Allow/control read-only access

### ISSUE THREAD

**Issue by seebs** [sourcegraph/src-cli#7]
Access token options now are (1) full access as a given user, (2) full access as anyone.

The discussion of documenting access tokens mentions in passing that you don't need to log in to use sourcegraph.com in general. It seems like it might make sense to have a configuration flag for whether or not to permit tokenless read-only access, but also to have a way to generate read-only tokens which aren't allowed to do things.

This is really hard. Consider a hypothetical attacker who finds out about a thing that can be triggered if they can induce your sourcegraph instance to do a git fetch of a repo; a "read-only" token that can cause fetches is still a vulnerability. But it'd be nice to have, if we could do it.

**Comment by slimsag** [comment]
I think you're absolutely right (and as you've seen we have internal issues tracking this a bit).

The more general CLI-specific case of allowing access without a token, though, is #5 I think.

Since there isn't actually an implementation of these on the server-side of Sourcegraph yet, I'm going to close this issue and we can re-open if there is any work needed here later (but I suspect it'll 'just work').
