### ISSUE TITLE
Selecting src-cli version

### ISSUE THREAD

**Issue by DaedalusG** [sourcegraph/src-cli#849]
Currently its unclear how a user can selectively run a version of `src-cli`, additionally its possible to get the version state into `dev` mode and then -- to my knowledge you've got to delete the binary to and reinstall to get to a more current version.

We should have either more explicit documentation on our advised upgrade path for `src-cli` or we should provide more expansive functionality under `src version` to control the version of `src-cli` 

Its anecdotal but I've run into a number of folks having issues with this in the past

**Comment by mrnugget** [comment]
I'd say that version management is out of scope for `src-cli` itself. An `asdf` plugin, for example, seems to be the better choice. We also publish `src-cli` for Homebrew, which _should_ allow users to select which version they want to install: https://github.com/sourcegraph/homebrew-src-cli

So my question is: is this a _user_ problem or a _dev_ problem? If it's the latter, I want to say (and I know it's not helpful) that: "hmm, that's often how it is" You use dev builds, you need to manage them, you need to reinstall and fix, etc.

**Comment by DaedalusG** [comment]
I hear you with the dev problem part of this -- on at least one occasion though, I've encountered a scenario where our release was having problems and this resulted in a users EC2 environment running an inconsistent version of `src-cli` -- clearly theres more context there, but in the occasion a strong formal way to specify the version you want to install or run in would have been good to have. Will leave open in case anyone else has opinions on this.

**Comment by courier-new** [comment]
Hey! I totally missed this issue, but funny enough, around this same time we actually introduced [versioned publishing to Homebrew](https://github.com/sourcegraph/src-cli/issues/862), which allows installing `src-cli` at a specific version, for example `brew install sourcegraph/src-cli/src-cli@4.0.2`, rather than needing to find the version indirectly via the Homebrew formula commit history. This doesn't _exactly_ solve the dev problem where you want to have multiple versions installed at the same time, but it should make that easier, and it does formalize how to install a previous version and is [explained in our docs](https://github.com/sourcegraph/src-cli#version-compatible-with-your-sourcegraph-instance). How is that for you?

**Comment by DaedalusG** [comment]
Yeah I think we can close this now, it'd be cool to have a `src upgrade` command or something but it's not essential

**Comment by courier-new** [comment]
Okay cool, yeah, thanks for the input! 🙂
